name: itm_connect
description: Official ITM Connect App – Admin & User Panel
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ UI & Design Libraries
  flutter_animate: ^4.3.0
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0
  dotted_border: ^2.0.0
  lottie: ^2.6.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.1.1

  # ✅ Utility Libraries
  collection: ^1.18.0
  image_picker: ^1.1.0
  file_picker: ^10.2.0

  # ✅ Map Integration (for Contact or Campus View)
  google_maps_flutter: ^2.5.0
  intl: ^0.20.2

  # ✅ (Future) Firebase Integration – Uncomment when ready
  # firebase_core: ^2.27.0
  # cloud_firestore: ^4.15.0
  # firebase_auth: ^4.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/Itm_logo.png
    - assets/animations/intro.json
