name: itm_connect
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

  provider: ^6.1.2
  cupertino_icons: ^1.0.6

  # Firebase core
  firebase_core: ^2.31.0
  # Analytics
  firebase_analytics: ^10.10.7

  # Auth
  firebase_auth: ^4.19.6

  # Firestore
  cloud_firestore: ^4.17.5

  # Cloud Functions client (for callable functions)
  cloud_functions: ^4.7.6

  # File picker (used in manage_teachers)
  file_picker: ^8.0.5

  # Iconsax (used in user_drawer, routine/profile screens)
  iconsax: ^0.0.8

  # Animations used across user screens (animate(), FadeEffect, SlideEffect, ms)
  flutter_animate: ^4.5.2

  # Date formatting used in class_routine and teacher list/profile
  intl: ^0.19.0

  # Font Awesome used in universal_drawer
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.2
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
