// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_c1kjRmZQhT-1ZSoBDIThHTQTNJpGWaI',
    appId: '1:737405241756:web:ac72fd244188ea64762059',
    messagingSenderId: '737405241756',
    projectId: 'itm-connect-app-2025',
    authDomain: 'itm-connect-app-2025.firebaseapp.com',
    storageBucket: 'itm-connect-app-2025.firebasestorage.app',
    measurementId: 'G-7VBQYXDMB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_OD6peSGT9k0UqFA1_mRAj30jvBs1ELM',
    appId: '1:737405241756:android:13ecbfa859bec875762059',
    messagingSenderId: '737405241756',
    projectId: 'itm-connect-app-2025',
    storageBucket: 'itm-connect-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYnuY9IjjXaFwTkLF7yi6SdeHamzJsiM',
    appId: '1:737405241756:ios:fbc680a7e90d2bc6762059',
    messagingSenderId: '737405241756',
    projectId: 'itm-connect-app-2025',
    storageBucket: 'itm-connect-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );
}
